#!/usr/bin/env python3
"""
gen-skills-readme.py — okhp3-skill-cataloger v1.1.0
OverKill Hill P³ · https://overkillhill.com · https://github.com/OKHP3
=======================================================
Bundled with the okhp3-skill-cataloger Agent Skill.
Canonical source: scripts/gen-skills-readme.py at project root.
Keep both copies in sync when updating.

Scans .agents/skills/, parses SKILL.md frontmatter, and regenerates the
catalog table in .agents/skills/README.md between marker comments.
Also writes .agents/skills/.catalog-meta.json for programmatic consumption.

No external dependencies. Python 3.9+ only.

Usage:
    python3 scripts/gen-skills-readme.py
    python3 scripts/gen-skills-readme.py --skills-dir .agents/skills
    python3 scripts/gen-skills-readme.py --mode library
    python3 scripts/gen-skills-readme.py --dry-run
    python3 scripts/gen-skills-readme.py --check
    python3 scripts/gen-skills-readme.py --json
    python3 scripts/gen-skills-readme.py --quiet

v1.1.0 additions over v1.0.0:
  - --mode auto (default): auto-detects project vs library layout
  - --dry-run: preview output without writing files
  - Writes .catalog-meta.json alongside README on every successful run
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# ── Constants ─────────────────────────────────────────────────────────────────

VERSION        = "1.1.0"
OKHP3_HOMEPAGE = "https://overkillhill.com"
OKHP3_GITHUB   = "https://github.com/OKHP3"

START_MARKER   = "<!-- SKILLS_CATALOG_START -->"
END_MARKER     = "<!-- SKILLS_CATALOG_END -->"
WARN_COMMENT   = (
    "<!-- ⚠️ DO NOT EDIT THIS SECTION MANUALLY"
    " — regenerated by scripts/gen-skills-readme.py -->"
)


# ── Frontmatter parser (zero external dependencies) ──────────────────────────

def _strip_quotes(value: str) -> str:
    """Remove surrounding single or double quotes from a YAML string value."""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
        return value[1:-1]
    return value


def parse_frontmatter(filepath: Path) -> dict:
    """
    Parse YAML frontmatter from a SKILL.md file without any external libraries.
    Handles: scalar strings, block scalars (> and |), nested dicts (2-space indent).
    """
    try:
        text = filepath.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return {}

    match = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not match:
        return {}

    raw = match.group(1)
    result: dict = {}
    current_key: str | None = None
    current_block: list[str] = []
    in_block = False
    nested_key: str | None = None
    nested_dict: dict = {}
    in_nested = False
    indent_level = 2

    for line in raw.splitlines():
        # Block scalar continuation
        if in_block:
            if line.startswith(" " * indent_level) or line.strip() == "":
                current_block.append(line.strip())
                continue
            result[current_key] = " ".join(current_block).strip()
            current_block, in_block = [], False

        # Nested dict continuation
        if in_nested and line.startswith("  "):
            sub = re.match(r"  ([^:]+):\s*(.*)", line)
            if sub:
                nested_dict[sub.group(1).strip()] = _strip_quotes(
                    sub.group(2).strip()
                )
            continue
        if in_nested and not line.startswith("  "):
            result[nested_key] = nested_dict
            nested_dict, nested_key, in_nested = {}, None, False

        kv = re.match(r"^([^:]+):\s*(.*)", line)
        if not kv:
            continue
        key, value = kv.group(1).strip(), kv.group(2).strip()

        if value in ("|", ">"):
            current_key, in_block = key, True
        elif value == "":
            nested_key, in_nested = key, True
        else:
            result[key] = _strip_quotes(value)

    if in_block and current_block:
        result[current_key] = " ".join(current_block).strip()
    if in_nested and nested_dict:
        result[nested_key] = nested_dict

    return result


# ── Mode detection ────────────────────────────────────────────────────────────

def detect_mode(skills_dir: Path) -> str:
    """
    Auto-detect whether skills_dir uses project (flat) or library (categorized) layout.

    Project mode:  .agents/skills/skill-name/SKILL.md
    Library mode:  .agents/skills/category/skill-name/SKILL.md

    Strategy: examine the first non-hidden subdirectory.
    - If it contains a SKILL.md directly → project mode
    - If it contains subdirectories (not a SKILL.md directly) → library mode
    - Default: project
    """
    for d in sorted(skills_dir.iterdir()):
        if not d.is_dir() or d.name.startswith("."):
            continue
        if (d / "SKILL.md").exists():
            return "project"
        # Check one level deeper for library pattern
        for sub in sorted(d.iterdir()):
            if sub.is_dir() and (sub / "SKILL.md").exists():
                return "library"
        # First subdir had neither SKILL.md nor skill subdirs — keep scanning
    return "project"


# ── Skill discovery ───────────────────────────────────────────────────────────

def discover_skills(skills_dir: Path, mode: str) -> list[dict]:
    """
    Find all skills under skills_dir for the given mode.

    project: skill-name/SKILL.md  (flat, one level)
    library: category/skill-name/SKILL.md  (categorized, two levels)
    """
    skills = []

    if mode == "library":
        for cat_dir in sorted(skills_dir.iterdir()):
            if not cat_dir.is_dir() or cat_dir.name.startswith("."):
                continue
            for skill_dir in sorted(cat_dir.iterdir()):
                if not skill_dir.is_dir():
                    continue
                md = skill_dir / "SKILL.md"
                if md.exists():
                    fm = parse_frontmatter(md)
                    skills.append(_record(skill_dir, md, fm, cat_dir.name, skills_dir))
    else:
        # project / flat
        for skill_dir in sorted(skills_dir.iterdir()):
            if not skill_dir.is_dir() or skill_dir.name.startswith("."):
                continue
            md = skill_dir / "SKILL.md"
            if md.exists():
                fm = parse_frontmatter(md)
                meta = fm.get("metadata", {})
                cat = (meta.get("category", "—") if isinstance(meta, dict) else "—")
                skills.append(_record(skill_dir, md, fm, cat, skills_dir))

    return skills


def _record(
    skill_dir: Path,
    skill_md: Path,
    fm: dict,
    category: str,
    base_dir: Path,
) -> dict:
    meta = fm.get("metadata", {})
    if not isinstance(meta, dict):
        meta = {}

    name      = fm.get("name", skill_dir.name)
    raw_desc  = fm.get("description", "")
    desc      = re.sub(r"\s+", " ", raw_desc).strip()
    if len(desc) > 100:
        desc = desc[:97] + "..."

    return {
        "name":          name,
        "dir_name":      skill_dir.name,
        "description":   desc,
        "version":       meta.get("version", "—"),
        "category":      category,
        "origin":        meta.get("origin", "—"),
        "path":          str(skill_md.relative_to(base_dir)),
        "name_mismatch": name != skill_dir.name,
    }


# ── Table / section generation ────────────────────────────────────────────────

def project_table(skills: list[dict]) -> str:
    if not skills:
        return "_No skills installed yet._"
    rows = [
        "| Skill | Description | Version | Category |",
        "|---|---|---|---|",
    ]
    for s in skills:
        warn = " ⚠️" if s["name_mismatch"] else ""
        link = f"[{s['name']}]({s['path']})"
        rows.append(
            f"| {link}{warn} | {s['description']} | {s['version']} | {s['category']} |"
        )
    return "\n".join(rows)


def library_sections(skills: list[dict]) -> str:
    if not skills:
        return "_No skills in the library yet._"
    cats: dict[str, list[dict]] = {}
    for s in skills:
        cats.setdefault(s["category"], []).append(s)
    parts = []
    for cat in sorted(cats):
        items = sorted(cats[cat], key=lambda x: x["name"])
        n = len(items)
        parts += [
            f"### {cat} ({n} skill{'s' if n != 1 else ''})",
            "",
            "| Skill | Description | Version |",
            "|---|---|---|",
        ] + [
            f"| [{'⚠️ ' if s['name_mismatch'] else ''}{s['name']}]({s['path']}) "
            f"| {s['description']} | {s['version']} |"
            for s in items
        ] + [""]
    return "\n".join(parts)


def build_block(skills: list[dict], mode: str) -> str:
    now      = datetime.now(timezone.utc)
    now_iso  = now.strftime("%Y-%m-%d %H:%M UTC")
    now_disp = now.strftime("%B %-d, %Y at %H:%M UTC")
    n    = len(skills)
    sw   = "skill" if n == 1 else "skills"
    cats = len({s["category"] for s in skills})

    lines = [START_MARKER, WARN_COMMENT]
    if mode == "library":
        lines.append(
            f"<!-- Generated: {now_iso} | Skills: {n} | Categories: {cats} | Mode: library -->"
        )
        lines += [
            "",
            f"*Catalog last updated: **{now_disp}** &nbsp;·&nbsp; "
            f"**{n}** {sw} across **{cats}** categories*",
            "",
            library_sections(skills),
        ]
    else:
        lines.append(
            f"<!-- Generated: {now_iso} | Skills: {n} | Mode: project -->"
        )
        lines += [
            "",
            f"*Catalog last updated: **{now_disp}** &nbsp;·&nbsp; **{n}** {sw} indexed*",
            "",
            project_table(skills),
            "",
        ]
    lines.append(END_MARKER)
    return "\n".join(lines)


# ── README injection ──────────────────────────────────────────────────────────

def inject(readme: Path, block: str) -> tuple[bool, str]:
    """
    Replace content between START_MARKER and END_MARKER in the README.
    Returns (changed, new_content). Raises on missing file or missing markers.
    """
    if not readme.exists():
        raise FileNotFoundError(
            f"{readme} not found.\n"
            "Create it with the catalog markers before first run:\n"
            "  <!-- SKILLS_CATALOG_START -->\n"
            "  <!-- SKILLS_CATALOG_END -->"
        )
    content = readme.read_text(encoding="utf-8")
    s = content.find(START_MARKER)
    e = content.find(END_MARKER)
    if s == -1 or e == -1:
        raise ValueError(
            f"Catalog markers not found in {readme}.\n"
            "Add these two lines where the catalog should appear:\n"
            "  <!-- SKILLS_CATALOG_START -->\n"
            "  <!-- SKILLS_CATALOG_END -->"
        )
    new = content[:s] + block + "\n" + content[e + len(END_MARKER):]
    return new != content, new


# ── .catalog-meta.json ────────────────────────────────────────────────────────

def write_catalog_meta(skills_dir: Path, skills: list[dict], mode: str) -> None:
    """
    Write a machine-readable JSON metadata file alongside the catalog README.
    Useful for CI checks, dashboards, or tooling that needs catalog state
    without parsing Markdown.
    """
    now = datetime.now(timezone.utc)
    meta = {
        "last_indexed":  now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "skill_count":   len(skills),
        "mode":          mode,
        "indexed_by":    f"okhp3-skill-cataloger v{VERSION}",
        "homepage":      OKHP3_HOMEPAGE,
        "github":        OKHP3_GITHUB,
    }
    (skills_dir / ".catalog-meta.json").write_text(
        json.dumps(meta, indent=2) + "\n", encoding="utf-8"
    )


# ── Validation ────────────────────────────────────────────────────────────────

def validate(skills: list[dict]) -> tuple[list[str], list[str]]:
    """
    Validate skills. Returns (errors, warnings).
    errors   → fatal: stop before generating
    warnings → non-fatal: show and continue
    """
    errors:   list[str] = []
    warnings: list[str] = []
    seen: dict[str, str] = {}

    for s in skills:
        if s["name_mismatch"]:
            errors.append(
                f"  ✗ [{s['dir_name']}] frontmatter name '{s['name']}' "
                f"!= directory name '{s['dir_name']}'"
            )
        if s["name"] in seen:
            errors.append(
                f"  ✗ Duplicate name '{s['name']}' in '{s['dir_name']}' "
                f"and '{seen[s['name']]}'"
            )
        seen[s["name"]] = s["dir_name"]
        if not s["description"] or s["description"] == "—":
            errors.append(f"  ✗ [{s['name']}] no description in frontmatter")
        if s["version"] == "—":
            warnings.append(f"  ⚠ [{s['name']}] no version in metadata")

    return errors, warnings


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> int:
    p = argparse.ArgumentParser(
        description=f"okhp3-skill-cataloger v{VERSION} — regenerate .agents/skills/README.md",
        epilog=f"OverKill Hill P³ · {OKHP3_HOMEPAGE} · {OKHP3_GITHUB}",
    )
    p.add_argument(
        "--skills-dir", default=".agents/skills",
        help="Path to the skills root directory (default: .agents/skills)",
    )
    p.add_argument(
        "--mode", choices=["project", "library", "auto"], default="auto",
        help=(
            "Catalog mode: project (flat), library (categorized), "
            "auto (detect from layout — default)"
        ),
    )
    p.add_argument(
        "--dry-run", action="store_true",
        help="Print output to stdout without writing any files",
    )
    p.add_argument(
        "--check", action="store_true",
        help="Validate skills and markers only — do not write README",
    )
    p.add_argument(
        "--json", action="store_true",
        help="Print machine-readable JSON skill list to stdout and exit",
    )
    p.add_argument(
        "--quiet", action="store_true",
        help="Suppress informational output; only print errors",
    )
    args = p.parse_args()

    skills_dir = Path(args.skills_dir)
    readme     = skills_dir / "README.md"

    if not skills_dir.exists():
        print(f"✗ Not found: {skills_dir}", file=sys.stderr)
        sys.exit(1)

    # ── Resolve mode ──────────────────────────────────────────────────────────
    if args.mode == "auto":
        mode = detect_mode(skills_dir)
        if not args.quiet and not args.json:
            print(f"Auto-detected mode: {mode}")
    else:
        mode = args.mode

    # ── Discover ──────────────────────────────────────────────────────────────
    skills = discover_skills(skills_dir, mode)

    if args.json:
        print(json.dumps(skills, indent=2))
        return 0

    if not args.quiet:
        print(f"Found {len(skills)} skill(s) in {skills_dir} [{mode} mode]")

    # ── Validate ──────────────────────────────────────────────────────────────
    errors, warnings = validate(skills)

    if warnings and not args.quiet:
        print("\nValidation warnings:")
        for w in warnings:
            print(w)

    if errors:
        print("\nValidation errors:")
        for e in errors:
            print(e)
        print("\n✗ Fix errors before generating.", file=sys.stderr)
        return 1

    # ── Check-only mode ───────────────────────────────────────────────────────
    if args.check:
        if readme.exists():
            c = readme.read_text(encoding="utf-8")
            if START_MARKER not in c or END_MARKER not in c:
                print(f"✗ README missing catalog markers.", file=sys.stderr)
                return 1
        if not args.quiet:
            print("✓ Check passed.")
        return 0

    # ── Build block ───────────────────────────────────────────────────────────
    block = build_block(skills, mode)

    # ── Dry run ───────────────────────────────────────────────────────────────
    if args.dry_run:
        print("\n" + "─" * 60)
        print(f"DRY RUN — would write to: {readme}")
        print("─" * 60)
        print(block)
        print("─" * 60)
        print(f"\nDRY RUN — would write: {skills_dir / '.catalog-meta.json'}")
        print(f"Dry run complete. {len(skills)} skill(s) would be indexed.")
        return 0

    # ── Inject into README ────────────────────────────────────────────────────
    try:
        changed, new_content = inject(readme, block)
    except (FileNotFoundError, ValueError) as exc:
        print(f"✗ {exc}", file=sys.stderr)
        return 1

    if changed:
        readme.write_text(new_content, encoding="utf-8")
        if not args.quiet:
            print(f"✓ Updated: {readme}")
    else:
        if not args.quiet:
            print("✓ Already current — no changes written.")

    # ── Write .catalog-meta.json ──────────────────────────────────────────────
    write_catalog_meta(skills_dir, skills, mode)
    if not args.quiet:
        print(f"✓ Written: {skills_dir / '.catalog-meta.json'}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
