#!/usr/bin/env python3
"""
gen-skills-readme.py — okhp3-skill-cataloger
OverKill Hill P³ · https://overkillhill.com · https://github.com/OKHP3
=======================================================
Bundled with the okhp3-skill-cataloger Agent Skill.
Canonical source: scripts/gen-skills-readme.py at project root.
Keep both copies in sync when updating.

Scans .agents/skills/, parses SKILL.md frontmatter, and regenerates the
catalog table in .agents/skills/README.md between marker comments.

No external dependencies. Python 3.9+ only.

Usage:
    python3 scripts/gen-skills-readme.py
    python3 scripts/gen-skills-readme.py --skills-dir .agents/skills
    python3 scripts/gen-skills-readme.py --mode library
    python3 scripts/gen-skills-readme.py --check
    python3 scripts/gen-skills-readme.py --json
    python3 scripts/gen-skills-readme.py --quiet
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

START_MARKER = "<!-- SKILLS_CATALOG_START -->"
END_MARKER   = "<!-- SKILLS_CATALOG_END -->"
WARN_COMMENT = ("<!-- ⚠️ DO NOT EDIT THIS SECTION MANUALLY"
                " — regenerated by scripts/gen-skills-readme.py -->")


def _strip_quotes(value: str) -> str:
    """Remove surrounding single or double quotes from a YAML string value."""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
        return value[1:-1]
    return value


# ── Frontmatter parser (no PyYAML) ──────────────────────────────────────────

def parse_frontmatter(filepath: Path) -> dict:
    try:
        text = filepath.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return {}

    match = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not match:
        return {}

    raw = match.group(1)
    result: dict = {}
    current_key: str | None = None
    current_block: list[str] = []
    in_block = False
    nested_key: str | None = None
    nested_dict: dict = {}
    in_nested = False
    indent_level = 2

    for line in raw.splitlines():
        # Block scalar continuation
        if in_block:
            if line.startswith(" " * indent_level) or line.strip() == "":
                current_block.append(line.strip())
                continue
            result[current_key] = " ".join(current_block).strip()
            current_block, in_block = [], False

        # Nested dict continuation
        if in_nested and line.startswith("  "):
            sub = re.match(r"  ([^:]+):\s*(.*)", line)
            if sub:
                nested_dict[sub.group(1).strip()] = _strip_quotes(sub.group(2).strip())
            continue
        if in_nested and not line.startswith("  "):
            result[nested_key] = nested_dict
            nested_dict, nested_key, in_nested = {}, None, False

        kv = re.match(r"^([^:]+):\s*(.*)", line)
        if not kv:
            continue
        key, value = kv.group(1).strip(), kv.group(2).strip()

        if value in ("|", ">"):
            current_key, in_block = key, True
        elif value == "":
            nested_key, in_nested = key, True
        else:
            result[key] = _strip_quotes(value)

    if in_block and current_block:
        result[current_key] = " ".join(current_block).strip()
    if in_nested and nested_dict:
        result[nested_key] = nested_dict

    return result


# ── Skill discovery ──────────────────────────────────────────────────────────

def discover_skills(skills_dir: Path, mode: str) -> list[dict]:
    skills = []

    if mode == "library":
        # category/skill-name/SKILL.md
        for cat_dir in sorted(skills_dir.iterdir()):
            if not cat_dir.is_dir() or cat_dir.name.startswith("."):
                continue
            for skill_dir in sorted(cat_dir.iterdir()):
                if not skill_dir.is_dir():
                    continue
                md = skill_dir / "SKILL.md"
                if md.exists():
                    fm = parse_frontmatter(md)
                    skills.append(_record(skill_dir, md, fm, cat_dir.name, skills_dir))
    else:
        # skill-name/SKILL.md  (flat)
        for skill_dir in sorted(skills_dir.iterdir()):
            if not skill_dir.is_dir() or skill_dir.name.startswith("."):
                continue
            md = skill_dir / "SKILL.md"
            if md.exists():
                fm = parse_frontmatter(md)
                cat = (fm.get("metadata", {}) or {}).get("category", "—")
                if isinstance(fm.get("metadata"), str):
                    cat = "—"
                skills.append(_record(skill_dir, md, fm, cat, skills_dir))

    return skills


def _record(skill_dir, skill_md, fm, category, base_dir) -> dict:
    meta = fm.get("metadata", {})
    if not isinstance(meta, dict):
        meta = {}
    name = fm.get("name", skill_dir.name)
    raw_desc = fm.get("description", "")
    description = re.sub(r"\s+", " ", raw_desc).strip()
    if len(description) > 100:
        description = description[:97] + "..."
    return {
        "name":          name,
        "dir_name":      skill_dir.name,
        "description":   description,
        "version":       meta.get("version", "—"),
        "category":      category,
        "origin":        meta.get("origin", "—"),
        "path":          str(skill_md.relative_to(base_dir)),
        "name_mismatch": name != skill_dir.name,
    }


# ── Table / section generation ───────────────────────────────────────────────

def project_table(skills: list[dict]) -> str:
    if not skills:
        return "_No skills installed yet._"
    rows = [
        "| Skill | Description | Version | Category |",
        "|---|---|---|---|",
    ]
    for s in skills:
        warn = " ⚠️" if s["name_mismatch"] else ""
        link = f"[{s['name']}]({s['path']})"
        rows.append(f"| {link}{warn} | {s['description']} | {s['version']} | {s['category']} |")
    return "\n".join(rows)


def library_sections(skills: list[dict]) -> str:
    if not skills:
        return "_No skills in the library yet._"
    cats: dict[str, list[dict]] = {}
    for s in skills:
        cats.setdefault(s["category"], []).append(s)
    parts = []
    for cat in sorted(cats):
        items = sorted(cats[cat], key=lambda x: x["name"])
        parts += [
            f"### {cat} ({len(items)} skill{'s' if len(items) != 1 else ''})", "",
            "| Skill | Description | Version |",
            "|---|---|---|",
        ] + [
            f"| [{'⚠️ ' if s['name_mismatch'] else ''}{s['name']}]({s['path']}) "
            f"| {s['description']} | {s['version']} |"
            for s in items
        ] + [""]
    return "\n".join(parts)


def build_block(skills: list[dict], mode: str) -> str:
    now      = datetime.now(timezone.utc)
    now_iso  = now.strftime("%Y-%m-%d %H:%M UTC")
    now_disp = now.strftime("%B %-d, %Y at %H:%M UTC")
    cats = len({s["category"] for s in skills})
    n    = len(skills)
    sw   = "skill" if n == 1 else "skills"

    lines = [START_MARKER, WARN_COMMENT]
    if mode == "library":
        lines.append(f"<!-- Generated: {now_iso} | Skills: {n} | Categories: {cats} -->")
        lines += [
            "",
            f"*Catalog last updated: **{now_disp}** &nbsp;·&nbsp; "
            f"**{n}** {sw} across **{cats}** categories*",
            "",
            library_sections(skills),
        ]
    else:
        lines.append(f"<!-- Generated: {now_iso} | Skills: {n} -->")
        lines += [
            "",
            f"*Catalog last updated: **{now_disp}** &nbsp;·&nbsp; **{n}** {sw} indexed*",
            "",
            project_table(skills),
            "",
        ]
    lines.append(END_MARKER)
    return "\n".join(lines)


# ── README injection ─────────────────────────────────────────────────────────

def inject(readme: Path, block: str) -> tuple[bool, str]:
    if not readme.exists():
        raise FileNotFoundError(str(readme))
    content = readme.read_text(encoding="utf-8")
    s = content.find(START_MARKER)
    e = content.find(END_MARKER)
    if s == -1 or e == -1:
        raise ValueError(
            f"Markers not found in {readme}.\n"
            f"Initialize the README from the project template first."
        )
    new = content[:s] + block + "\n" + content[e + len(END_MARKER):]
    return new != content, new


# ── Validation ───────────────────────────────────────────────────────────────

def validate(skills: list[dict]) -> list[str]:
    errors, seen = [], {}
    for s in skills:
        if s["name_mismatch"]:
            errors.append(
                f"  ✗ [{s['dir_name']}] frontmatter name '{s['name']}' "
                f"!= directory name '{s['dir_name']}'"
            )
        if s["name"] in seen:
            errors.append(f"  ✗ Duplicate name '{s['name']}' in '{s['dir_name']}' "
                          f"and '{seen[s['name']]}'")
        seen[s["name"]] = s["dir_name"]
        if not s["description"] or s["description"] == "—":
            errors.append(f"  ✗ [{s['name']}] no description in frontmatter")
        if s["version"] == "—":
            errors.append(f"  ⚠ [{s['name']}] no version in metadata")
    return errors


# ── Entry point ──────────────────────────────────────────────────────────────

def main():
    p = argparse.ArgumentParser(description="Regenerate .agents/skills/README.md catalog")
    p.add_argument("--skills-dir", default=".agents/skills")
    p.add_argument("--mode", choices=["project", "library"], default="project")
    p.add_argument("--check", action="store_true", help="Validate only, no write")
    p.add_argument("--json",  action="store_true", help="Print JSON to stdout")
    p.add_argument("--quiet", action="store_true", help="Suppress non-error output")
    args = p.parse_args()

    skills_dir = Path(args.skills_dir)
    readme     = skills_dir / "README.md"

    if not skills_dir.exists():
        print(f"✗ Not found: {skills_dir}", file=sys.stderr); sys.exit(1)

    skills = discover_skills(skills_dir, args.mode)

    if args.json:
        print(json.dumps(skills, indent=2)); return

    if not args.quiet:
        print(f"Found {len(skills)} skill(s) in {skills_dir}")

    errors = validate(skills)
    if errors:
        print("\nValidation issues:")
        for e in errors: print(e)
        if any(e.strip().startswith("✗") for e in errors):
            print("\n✗ Fix errors before generating.", file=sys.stderr); sys.exit(1)

    if args.check:
        if readme.exists():
            c = readme.read_text(encoding="utf-8")
            if START_MARKER not in c or END_MARKER not in c:
                print(f"✗ README missing catalog markers.", file=sys.stderr); sys.exit(1)
        print("✓ Check passed."); return

    block = build_block(skills, args.mode)
    try:
        changed, new_content = inject(readme, block)
    except (FileNotFoundError, ValueError) as exc:
        print(f"✗ {exc}", file=sys.stderr); sys.exit(1)

    if changed:
        readme.write_text(new_content, encoding="utf-8")
        if not args.quiet: print(f"✓ Updated: {readme}")
    else:
        if not args.quiet: print("✓ Already current — no changes written.")


if __name__ == "__main__":
    main()
