// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ExploreB.tsx": () => import("../components/mockups/ExploreB.tsx"),
  "./components/mockups/ExploreD.tsx": () => import("../components/mockups/ExploreD.tsx"),
  "./components/mockups/ExploreE.tsx": () => import("../components/mockups/ExploreE.tsx"),
  "./components/mockups/ExploreF.tsx": () => import("../components/mockups/ExploreF.tsx"),
  "./components/mockups/ForgeWorkbench.tsx": () => import("../components/mockups/ForgeWorkbench.tsx"),
  "./components/mockups/HomeA.tsx": () => import("../components/mockups/HomeA.tsx"),
  "./components/mockups/HomeB.tsx": () => import("../components/mockups/HomeB.tsx"),
  "./components/mockups/SkillDetailAudit.tsx": () => import("../components/mockups/SkillDetailAudit.tsx"),
  "./components/mockups/SkillDetailC.tsx": () => import("../components/mockups/SkillDetailC.tsx"),
  "./components/mockups/SkillDetailD.tsx": () => import("../components/mockups/SkillDetailD.tsx"),
  "./components/mockups/SkillDetailE.tsx": () => import("../components/mockups/SkillDetailE.tsx")
};
